version: '3.8'

services:
  mariadb:
    image: mysql:8.0.32
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MARIADB_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "openxeco"
      MYSQL_USER: "openxeco"
      MYSQL_PASSWORD: "openxeco-pwd"
    command:
      --sql_mode=STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION
    ports:
      - '3366:3306'
    expose:
      - '3366'
    volumes:
      - ./.docker/mariadb/data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "--silent" ]
      timeout: 5s
      retries: 10

  smtp:
    image: reachfive/fake-smtp-server
    ports:
      - "1025:1025"
      - "1080:1080"

  oxe-web-admin:
    image: openxeco-core_oxe-web-admin:local
    build:
      context: .
      dockerfile: oxe-web-admin/.docker/Dockerfile
    tty: true
    volumes:
      - ./oxe-web-admin:/usr/app
      - /usr/app/node_modules
    command: npm start
    ports:
      - "3000:3000"
    expose:
      - '3000'

  oxe-web-community:
    image: openxeco-core_oxe-web-community:local
    build:
      context: .
      dockerfile: oxe-web-community/.docker/Dockerfile
    tty: true
    volumes:
      - ./oxe-web-community:/usr/app
      - /usr/app/node_modules
    command: npm start
    ports:
      - "3001:3001"
    expose:
      - '3001'

  oxe-api:
    image: openxeco-core_oxe-api:local
    build:
      context: .
      dockerfile: oxe-api/.docker/Dockerfile
    restart: always
    volumes:
      - ./.docker/media:/usr/app/media
      - ./.docker/documents:/usr/app/documents
      - ./oxe-api:/usr/app
    ports:
      - "5000:5000"
    expose:
      - '5000'
    environment:
      DEBUG: "true"
      DB_HOSTNAME: "mariadb"
      DB_NAME: "openxeco"
      DB_USERNAME: "openxeco"
      DB_PASSWORD: "openxeco-pwd"
      DB_PORT: "3306"
      DB_DRIVER: "mysql+pymysql"
      JWT_SECRET_KEY: "some_random_secret"
      MAIL_SERVER: "smtp"
      MAIL_PORT: "1025"
      MAIL_USE_TLS: "False"
      MAIL_USE_SSL: "False"
      IMAGE_FOLDER: "/usr/app/media"
      DOCUMENT_FOLDER: "/usr/app/documents"
      MAIL_DEFAULT_SENDER: "openxeco@localhost.localdomain"
      INITIAL_ADMIN_EMAIL: "admin@localhost.localdomain"
    depends_on:
      mariadb:
        condition: service_healthy

networks:
  default:
    name: openxeco
