name: bo-api PyCQA Prospector
on:
  push:
    branches:
      - main
      - validation
    paths:
      - 'bo-api/**'
  pull_request:
    branches:
      - main
      - validation
    paths:
      - 'bo-api/**'

defaults:
  run:
    working-directory: bo-api/

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Python 3
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Run PyCQA Prospector
        run: |
          cp config/config.py.sample config/config.py
          prospector -i venv/ --no-autodetect
